services:
  wynil-bot:
    build: .
    container_name: wynil-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
    extra_hosts:
      - "host.docker.internal:host-gateway"